apiVersion: v2
publisher: Builder.io
name: my-vscode-ext
version: 1.7.2
type: value
displayName:
title:
description:
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository:
category:
spec:
  containers:
    - image:
      memoryLimit:
      memoryRequest:
      cpuLimit:
      cpuRequest:
  extensions:
          - https://marketplace.visualstudio.com/_apis/public/gallery/publishers/Builder/vsextensions/Builder/0.0.9/vspackage
